fototunc/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# home_view import ettik view.py adresinde olan
from home.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # sol taraf adres sağ taraf girilecek view
    path('', home_view),
    path('tracking/', include('tracking.urls')),
]

tracking/urls.py
from django.urls import path, re_path
# bütün traciking viewları içe aktardık
from .views import *
# çakışmayı engellemek için
app_name = 'tracking'

urlpatterns = [
    # sol taraf adres sağ taraf girilecek view
    path('index/', tracking_index, name='index'),
    path('create/', tracking_create, name='create'),
    # r'^ başlangıç belirtiyor /$ sonu belirtiyor
    # iç (?P<id>\d+) kısmı detail id yi sayfa ismi olarak belirliyoruz
    # re_path(r'^(?P<id>\d+)/detail/$', tracking_detail, name='detail'),
    # slug için güncelledik (w) her hangi bir karakter demek model ve view deki bütün id leri slug a çevirdik
    re_path(r'^(?P<slug>[\w-]+)/$', tracking_detail, name='detail'),
    # update için örnek tracking/4/update
    re_path(r'^(?P<slug>[\w-]+)/update/$', tracking_update, name='update'),
    # id alıp yönlendirme yapmak için
    re_path(r'^(?P<slug>[\w-]+)/delete/$', tracking_delete, name='delete'),
    re_path(r'^(?P<slug>[\w-]+)/ready/$', tracking_ready, name='ready'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse


# Create your views here.
# Ana sayfa düzenleme görünüm
# request kullanıcı ile ilgili bilgiler getiren parametre
# url bölümüne home_view import ettik

def home_view(request):
    # Eğer kullanıcı giriş yaptı ise ismini yazdır yapmadı ise Misafir olarak tanımla
    if request.user.is_authenticated:
        # içerikler birden fazla ise bu şekilde tanımlamak daha iyi olur
        # isim anahtar ilişkisine dayalı olacak
        context = {
            'isim': 'Oğuz',
        }
    else:
        context = {
            'isim': 'Misafir',
        }
    # home.html dosyası
    # home.html dosyasını templatesden home klasörüne çağırıyoruz
    # view fonksiyonlarından html dosyalarına içerik göndereceğiz içeriği dinamikleştirmek için
    return render(request, 'home.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Foto Tunç{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fixed.css'%}">
    <!--
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    -->
</head>

<body data-spy="scroll" data-target="#navbarResponsive">
    {% include 'header.html'  %}

    {% include 'messages.html' %}
    <!-- base template parent diğer templateler ise child templatetir. -->
    {% block body %}

    {% endblock %}

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"></script>

</body>
</html>

templates/header.html
<!-- Navigation -->
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarResponsive">
    <span class="navbar-toggler-icon"></span>
  </button>

  {% if request.user.is_authenticated %}
  <form class="form" action="http://127.0.0.1:8000/tracking/index/" method="get">
    <input class="form-style-navbar" type="search" placeholder="Müşteri ara" aria-label="Search" name="q" value="{{ request.GET.q }}">
    <button class="btn btn-outline-light btn-lg-header" type="submit">Ara</button>
  </form>
  {% endif %}

  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tracking:create' %}">Müşteri Ekle</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tracking:index' %}">Müşteri Listesi</a>
      </li>
      {% endif %}
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="/#home">Anasayfa</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#features">Fiyatlarımız</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#resources">Çekimler</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#clients">Hakkımızda</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#contact">İletişim</a>
      </li>

      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="/#home">Anasayfa</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#features">Fiyatlarımız</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#resources">Çekimler</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#clients">Hakkımızda</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#contact">İletişim</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

<!-- End Navigation -->

templates/home.html
<!-- base.html ile genişlettik -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Anasayfa - {{ block.super }}{% endblock %}
{% block body %}

<!-- Start Home Section -->
<div id="home">

<!-- Start Landing Page Section -->

<div class="landing">
  <div class="home-wrap">
    <div class="home-inner">

    </div>
  </div>
</div>

<div class="caption text-center">
  <h1>Tunç Fotoğrafcılık</h1>
  <h3>Resminizin Durumunu Öğrenmek İçin Takip Numaranızı Giriniz</h3>

  {% if request.user.is_authenticated %}
        <!-- Arama Çubuğu -->

        <form class="form" action="http://127.0.0.1:8000/tracking/index/" method="get">
            <input class="form-style" type="search" placeholder="Müşteri ara" aria-label="Search" name="q" value="{{ request.GET.q }}">
            <button class="btn btn-outline-light btn-lg" type="submit">Ara</button>
        </form>

        {% else %}

        <form class="form" action="http://127.0.0.1:8000/tracking/index/" method="get">
            <input class="form-style" type="search" placeholder="Takip numarası" aria-label="Search" name="q" value="{{ request.GET.q }}">
            <button class="btn btn-outline-light btn-lg" type="submit">Sorgula</button>
        </form>

  {% endif %}
</div>
<!-- End Landing Page Section  -->
</div>
<!-- End Home Section -->

<!-- Start Features Section -->
<div id="features" class="offset">

<!-- Start Jumbotron -->
  <div class="jumbotron">
    <!-- Start Narrow -->
    <div class="narrow text-center">
      <div class="col-12">
        <h3 class="heading">Fiyatlar</h3>
        <div class="heading-underline">

        </div>
      </div>

      <div class="row text-center">
        <div class="col-md-4">
          <div class="feature">
            <i class="fas fa-play-circle fa-4x" data-fa-transform="shrink-3 up-5"></i>
            <h3>Custom Animation</h3>
            <p>Animate.css and Waypoints.js allow for smooth animations scrolling down the site.</p>
          </div>
        </div>

        <div class="col-md-4">
          <div class="feature">
            <i class="fas fa-sliders-h fa-4x" data-fa-transform="shrink-4.5 up-4.5"></i>
            <h3>Content Slider</h3>
            <p>Animate.css and Waypoints.js allow for smooth animations scrolling down the site.</p>
          </div>
        </div>

        <div class="col-md-4">
          <div class="feature">
            <i class="fab fa-wpforms fa-4x" data-fa-transform="shrink-4.5 up-5"></i>
            <h3>Content From</h3>
            <p>Animate.css and Waypoints.js allow for smooth animations scrolling down the site.</p>
          </div>
        </div>
      </div>
      <!-- End Row -->
    </div>
    <!-- End Narrow -->
  </div>
<!-- End Jumbotron -->

</div>
<!-- End Features Section -->

<!-- Start resources Section -->
<div id="resources" class="offset">

  <div class="fixed-background">
    <div class="row dark text-center">
      <div class="col-12">
        <h3 class="heading">Çekimler</h3>
        <div class="heading-underline"></div>
      </div>

      <div class="col-md-4">
        <h3>HTML 5</h3>
        <div class="feature">
          <i class="fas fa-code fa-3x"></i>
        </div>
        <p class="lead">Built with the latest, HTML 5</p>
      </div>

      <div class="col-md-4">
        <h3>BOOTSTRAP 4</h3>
        <div class="feature">
          <i class="fas fa-bold fa-3x"></i>
        </div>
        <p class="lead">Built with the latest, BOOTSTRAP 4</p>
      </div>

      <div class="col-md-4">
        <h3>CSS 3</h3>
        <div class="feature">
          <i class="fab fa-css3 fa-3x"></i>
        </div>
        <p class="lead">Built with the latest, CSS 3</p>
      </div>
    </div>
    <!-- End Row Dark -->
    <div class="fixed-wrap">
      <div class="fixed">

      </div>
    </div>
  </div>
<!-- End Fixed Background -->
</div>
<!-- End resources Section -->

<!-- Start clients Section -->
<div id="clients" class="offset">

<!-- Start Jumbotron -->
<div class="jumbotron">
  <div class="col-12 text-center">
    <h3 class="heading">Hakkımızda</h3>
    <div class="heading-underline"></div>
  </div>

  <div class="row">

    <div class="col-md-6 clients">
      <div class="row">
        <div class="col-md-4">
          <img src="{% static 'img/client1.png' %}">
        </div>
        <div class="col-md-8">
          <blockquote>
            <i class="fas fa-quote-left"></i>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              <hr class="clients-hr">
              <cite>&#8212; Eric, Small Business Owner</cite>
          </blockquote>
        </div>
      </div>
    </div>

    <div class="col-md-6 clients">
      <div class="row">
        <div class="col-md-4">
          <img src="{% static 'img/client2.png' %}">
        </div>
        <div class="col-md-8">
          <blockquote>
            <i class="fas fa-quote-left"></i>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              <hr class="clients-hr">
              <cite>&#8212; Rachel, Professional Photographer</cite>
          </blockquote>
        </div>
      </div>
    </div>

  </div>
  <!-- End Row -->
</div>
<!-- End Jumbotron -->
</div>
<!-- End clients Section -->

<!-- Start contact Section -->
<div id="contact" class="offset">

    <div class="col-12 narrow text-center">
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12037.958984372164!2d28.826635!3d41.036418!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x53358c41245a61f0!2sFoto%20tunc!5e0!3m2!1str!2str!4v1569523477554!5m2!1str!2str"
            width="1000" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
    </div>
</div>

  <footer>
    <div class="row justify-content-center">
      <div class="col-md-5 text-center">
        <p>Güneşli, 63/B, Üsküp Cd, 34212 Bağcılar/İstanbul</p>
        <strong>İletişim Bilgileri</strong>
        <p>(212) 655-5565<br>studyotunc@windowslive.com</p>
        <a href="#" target="_blank"><i class="fab fa-facebook-square"></i></a>
        <a href="#" target="_blank"><i class="fab fa-twitter-square"></i></a>
        <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
      </div>

      <hr class="socket">
      &copy; Foto Tunç
    </div>
  </footer>

</div>
<!-- End contact Section -->

{% endblock %}

templates/messages.html
{% if messages %}
<div class="container">
<ul class="messages">
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
</ul>
</div>
{% endif %}